[package]
name = "adventcode2025"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "day1"
path = "day1/main.rs"

[[bin]]
name = "day2"
path = "src/day2/day2.rs"

[[bin]]
name = "day3part1"
path = "src/day3/day3part1.rs"

[[bin]]
name = "day3part2"
path = "src/day3/day3part2.rs"
